name: Generate Commit Info
description: 'Get the full commit information in current directory'

inputs:
  working-directory:
    description: 'The working directory to run the command'
    required: false
    default: '.'

outputs:
  commit_sha:
    description: 'The full commit SHA'
    value: ${{ steps.commit_info.outputs.commit_sha }}
  commit_author:
    description: 'The commit author'
    value: ${{ steps.commit_info.outputs.commit_author }}
  commit_message:
    description: 'The commit message'
    value: ${{ steps.commit_info.outputs.commit_message }}
  commit_date:
    description: 'The commit date'
    value: ${{ steps.commit_info.outputs.commit_date }}

runs:
  using: "composite"
  steps:
    - name: Get Commit Info
      working-directory: ${{ inputs.working-directory }}
      id: commit_info
      shell: bash
      run: |
        pwd
        # Get the full commit SHA
        full_sha=$(git rev-parse HEAD)
        
        # Get the commit author
        author=$(git log -1 --pretty=format:'%an')
        
        # Get the commit message
        message=$(git log -1 --pretty=format:'%s')
        
        # Get the commit date
        date=$(git log -1 --pretty=format:'%cd')
        
        # Set the commit info as outputs
        echo "commit_sha=$full_sha" >> $GITHUB_OUTPUT
        echo "commit_author=$author" >> $GITHUB_OUTPUT
        echo "commit_message=$message" >> $GITHUB_OUTPUT
        echo "commit_date=$date" >> $GITHUB_OUTPUT
