name: Generate Commit Info
description: 'Get the full commit information in current directory'

runs:
  using: "composite"
  steps:
    - name: Get Commit Info
      id: commit_info
      shell: bash
      run: |
        # Get the full commit SHA
        full_sha=$(git rev-parse HEAD)
        
        # Get the commit author
        author=$(git log -1 --pretty=format:'%an')
        
        # Get the commit message
        comment=$(git log -1 --pretty=format:'%s')
        
        # Get the commit date
        date=$(git log -1 --pretty=format:'%cd')
        
        # Set the commit info as outputs
        echo "::set-output name=commit_sha::$full_sha"
        echo "::set-output name=commit_author::$author"
        echo "::set-output name=commit_comment::$comment"
        echo "::set-output name=commit_date::$date"
