name: Generate Commit Info
description: 'Get the full commit information in current directory'

runs:
  using: "composite"
  steps:
    - name: Get Commit Info
      id: commit_info
      shell: bash
      run: |
        # Get the full commit SHA
        full_sha=$(git rev-parse HEAD)
        
        # Get the commit author
        author=$(git log -1 --pretty=format:'%an')
        
        # Get the commit message
        message=$(git log -1 --pretty=format:'%s')
        
        # Get the commit date
        date=$(git log -1 --pretty=format:'%cd')
        
        # Set the commit info as outputs
        echo "commit_sha=$full_sha" >> $GITHUB_OUTPUT
        echo "commit_author=$author" >> $GITHUB_OUTPUT
        echo "commit_message=$message" >> $GITHUB_OUTPUT
        echo "commit_date=$date" >> $GITHUB_OUTPUT
